version: '3.8'

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - '8080:80'
      - '81:81'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - backend

  haile_app:
    build:
      context: ./haile_server
      dockerfile: Dockerfile
    container_name: haile_service
    restart: unless-stopped
    env_file:
      - ./haile_server/.env
    volumes:
      - ./haile_server/machines.json:/app/machines.json:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge